/*
 * stm32l0xx_drivers_flags.h
 *
 *  Created on: 27 apr. 2026
 *      Author: Ludo
 */

#ifndef __STM32L0XX_DRIVERS_FLAGS_H__
#define __STM32L0XX_DRIVERS_FLAGS_H__

/*** STM32L0xx drivers compilation flags ***/

#define STM32L0XX_DRIVERS_DMA_CHANNEL_MASK              0x00

#define STM32L0XX_DRIVERS_EXTI_GPIO_MASK                0x0001

//#define STM32L0XX_DRIVERS_I2C_FAST_MODE

//#define STM32L0XX_DRIVERS_LPUART_RS485
//#define STM32L0XX_DRIVERS_LPUART_HIGH_BAUD_RATE
//#define STM32L0XX_DRIVERS_LPUART_DISABLE_TX_0

//#define STM32L0XX_DRIVERS_RCC_HSE_ENABLE
#define STM32L0XX_DRIVERS_RCC_HSE_FREQUENCY_HZ          16000000
#define STM32L0XX_DRIVERS_RCC_LSE_MODE                  0
#define STM32L0XX_DRIVERS_RCC_LSE_FREQUENCY_HZ          32768

#define STM32L0XX_DRIVERS_RTC_WAKEUP_PERIOD_SECONDS     10
#define STM32L0XX_DRIVERS_RTC_ALARM_MASK                0x00

#define STM32L0XX_DRIVERS_TIM_MODE_MASK                 0x04
#define STM32L0XX_DRIVERS_TIM_PRECISION                 0

//#define STM32L0XX_DRIVERS_USART_DISABLE_TX_0

#endif /* __STM32L0XX_DRIVERS_FLAGS_H__ */
