/*
 * embedded_utils_flags.h
 *
 *  Created on: 27 apr. 2026
 *      Author: Ludo
 */

#ifndef __EMBEDDED_UTILS_FLAGS_H__
#define __EMBEDDED_UTILS_FLAGS_H__

#include "usart.h"

/*** Embedded utility functions compilation flags ***/

#define EMBEDDED_UTILS_HW_INTERFACE_ERROR_BASE_LAST     USART_ERROR_BASE_LAST

#define EMBEDDED_UTILS_AT_DRIVER_DISABLE

#define EMBEDDED_UTILS_ERROR_STACK_DEPTH                32
#define EMBEDDED_UTILS_ERROR_STACK_SUCCESS_VALUE        0
//#define EMBEDDED_UTILS_ERROR_STACK_SIGFOX

#define EMBEDDED_UTILS_MATH_PRECISION                   0
//#define EMBEDDED_UTILS_MATH_COS_TABLE
//#define EMBEDDED_UTILS_MATH_SIN_TABLE
//#define EMBEDDED_UTILS_MATH_ATAN2

#define EMBEDDED_UTILS_STRING_HEXADECIMAL_UPPER_CASE

#define EMBEDDED_UTILS_TERMINAL_INSTANCES_NUMBER        0
#define EMBEDDED_UTILS_TERMINAL_BUFFER_SIZE             64
//#define EMBEDDED_UTILS_TERMINAL_MODE_BUS

#endif /* __EMBEDDED_UTILS_FLAGS_H__ */
